### ISSUE TITLE
How to Support

### ISSUE THREAD

**Issue by CaiB** [Aizistral-Studios/ForgeWorkspaceSetup#2]
Hello!

I just stumbled upon this after having dealt with the utter nightmare that is modding for Forge 1.7.10 for a while now. Every time I have tried interacting with the people at Forge, they have been nothing but toxic and unhelpful. However, I was able to set up and have something building with minimal effort using your system here, it's beyond fantastic.

I would like to give you some money to show my appreciation for actually caring, unlike the Forge team. I found a link for @juanmuscaria, but I could not find a way to support @Aizistral. Do you have a way for me to send you money?

Thank you for your work on this!!!

**Comment by Aizistral** [comment]
Oh, wow, I don't often get people wanting to support my work, especially in legacy modding space. You just melt my heart right there. Anyways, here's the link: https://www.buymeacoffee.com/aizistral

Also, I suggest that you visit CrucibleMC's discord server; that #modding channel right there is not the worst place to talk to people who also do some legacy modding and who can provide some actual help: https://discord.gg/ufVj6GhaSB

**Comment by CaiB** [comment]
<3
